Team creation front-end and some other things
gyorkistamas/afp2-2023-tavasz-stopinventing pull request #3
Opened 2023-03-27 06:21 UTC by BirGer05

2023-03-27 12:39 UTC, Banyik requested changes
There is a sign in form without any reason.

2023-03-27 12:39 UTC, Banyik commented on scrum_planner/resources/views/teams/creating_team.blade.php
> +        <form action={{ url('/sign-in') }} method="POST">
Why is this here?

2023-03-27 13:37 UTC, BirGer05 commented
Fixed the issu

2023-03-27 19:35 UTC, Banyik requested changes

2023-03-27 19:35 UTC, Banyik commented on scrum_planner/resources/views/teams/creating_team.blade.php
> +            </select>
What the ... is this?!

2023-03-31 16:01 UTC, BirGer05 commented on scrum_planner/resources/views/teams/creating_team.blade.php
> +            </select>
A simple place holder

2023-03-31 16:57 UTC, Banyik commented on scrum_planner/resources/views/teams/creating_team.blade.php
> +            </select>
This is not conventional, nor appropriate.

2023-03-31 16:57 UTC, Banyik requested changes
Bad placeholder

2023-03-31 17:04 UTC, BirGer05 commented
Removed all placeholder

2023-03-31 17:12 UTC, Banyik commented on scrum_planner/app/Http/Controllers/TeamController.php
> +            }
Missing error message

2023-03-31 17:13 UTC, Banyik requested changes
Missing error message on catch

2023-03-31 17:20 UTC, BirGer05 commented
It now counts how many user could not be added to the team, and shows it to the user creating the team

2023-03-31 17:21 UTC, Banyik approved these changes
finally

2023-03-31 17:26 UTC, merged